# Generated by Django 4.2.23 on 2026-05-26 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('card_uid', models.CharField(db_index=True, max_length=64)),
                ('card_token_hash', models.CharField(blank=True, max_length=128)),
                ('card_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('card_technology', models.CharField(choices=[('nfc_uid', 'NFC UID'), ('mifare_classic', 'MIFARE Classic'), ('mifare_desfire', 'MIFARE DESFire'), ('other', 'Outro')], default='nfc_uid', max_length=24)),
                ('status', models.CharField(choices=[('stock', 'Em Stock'), ('active', 'Activo'), ('blocked', 'Bloqueado'), ('lost', 'Perdido'), ('replaced', 'Substituido'), ('retired', 'Retirado')], default='stock', max_length=16)),
                ('issued_batch', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_cards', to='passengers.passengeraccount')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='cards.physicalcard')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_cards', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='cards_physi_status_6fcc0f_idx'), models.Index(fields=['card_uid', 'status'], name='cards_physi_card_ui_f236b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='physicalcard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('card_uid',), name='uq_card_uid_active'),
        ),
    ]
