# Generated by Django 4.2.23 on 2026-05-27 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('card_type', models.CharField(choices=[('physical', 'Fisico'), ('digital', 'Digital')], default='physical', max_length=16)),
                ('card_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('card_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('card_technology', models.CharField(choices=[('nfc_uid', 'NFC UID'), ('mifare_classic', 'MIFARE Classic'), ('mifare_desfire', 'MIFARE DESFire'), ('qr_code', 'QR Code'), ('other', 'Outro')], default='nfc_uid', max_length=24)),
                ('qr_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('qr_token_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('inactive', 'Inactivo'), ('active', 'Activo'), ('blocked', 'Bloqueado'), ('lost', 'Perdido'), ('replaced', 'Substituido'), ('retired', 'Retirado')], default='inactive', max_length=16)),
                ('issued_batch', models.CharField(blank=True, max_length=64)),
                ('batch_serial', models.CharField(blank=True, max_length=32)),
                ('manufacturer', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='physicalcard',
            name='passenger_account',
        ),
        migrations.RemoveField(
            model_name='physicalcard',
            name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='physicalcard',
            name='wallet',
        ),
    ]
