# Generated by Django 4.2.23 on 2026-05-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        ('passengers', '0001_initial'),
        ('validations', '0002_alter_validationevent_physical_card'),
        ('cards', '0002_card_remove_physicalcard_passenger_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalCard',
        ),
        migrations.AddField(
            model_name='card',
            name='passenger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='passengers.passengeraccount'),
        ),
        migrations.AddField(
            model_name='card',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='cards.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='wallets.wallet'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_type', 'status'], name='cards_card_card_ty_775f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_uid', 'status'], name='cards_card_card_ui_df61ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('card_uid',), name='uq_card_uid_active'),
        ),
    ]
