# Generated by Django 4.2.23 on 2026-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('template', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField()),
                ('purpose', models.CharField(blank=True, max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('failed', 'Falhada')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='sms_smsmess_phone_n_c46b6d_idx')],
            },
        ),
    ]
