# Generated by Django 4.2.23 on 2026-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['status', 'created_at'], name='sms_smsmess_status_636b8f_idx'),
        ),
    ]
