# Generated by Django 4.2.23 on 2026-08-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_service_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0011_triprevenueclosure_manifest_and_more'),
        ('sms', '0002_smsmessage_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('trip', 'Partida'), ('route', 'Rota')], max_length=8)),
                ('body', models.TextField()),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_broadcasts', to='routes.route')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_broadcasts', to='trips.trip')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['scope', 'created_at'], name='sms_smsbroa_scope_ffe867_idx')],
            },
        ),
    ]
