# Generated by Django 4.2.23 on 2026-05-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('app_type', models.CharField(choices=[('pos', 'POS'), ('passenger', 'Passageiro')], max_length=16)),
                ('version_name', models.CharField(max_length=32)),
                ('version_code', models.PositiveIntegerField()),
                ('apk_file', models.FileField(blank=True, upload_to='app-releases/')),
                ('apk_url', models.URLField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('release_notes', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('min_supported_version_code', models.PositiveIntegerField(default=0)),
                ('target_device_type', models.CharField(blank=True, max_length=24)),
                ('target_manufacturer', models.CharField(blank=True, max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('suspended', 'Suspenso'), ('retired', 'Retirado')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version_code',),
                'unique_together': {('app_type', 'version_code')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_version_code', models.PositiveIntegerField(default=0)),
                ('target_version_code', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('prompted', 'Notificado'), ('deferred', 'Adiado'), ('downloading', 'A Descarregar'), ('installed', 'Instalado'), ('failed', 'Falhado'), ('forced', 'Forcado')], default='pending', max_length=16)),
                ('prompted_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_until', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('app_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_updates', to='app_releases.apprelease')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_updates', to='devices.device')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('device', 'app_release')},
            },
        ),
    ]
