# Generated by Django 4.2.23 on 2026-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apprelease',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='apprelease',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('app_type', 'version_code'), name='uq_app_release_version_active'),
        ),
    ]
