# Generated by Django 4.2.23 on 2026-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_agent_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_role_code_active'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'role'), name='uq_user_role_active'),
        ),
    ]
