# Generated by Django 4.2.23 on 2026-08-15 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userrole_unique_together_alter_role_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True, help_text='Ao entrar no portal, pede um codigo enviado por SMS. So um superadministrador pode desligar.', verbose_name='Verificacao em dois passos'),
        ),
        migrations.CreateModel(
            name='PortalLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('consumed', 'Usado'), ('expired', 'Expirado')], default='pending', max_length=16)),
                ('code_hash', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_login_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='users_porta_user_id_a22f2c_idx')],
            },
        ),
            # Contas sem telemovel nao podem receber o codigo: se ficassem com o
        # 2FA ligado, ficavam trancadas de fora no primeiro login depois desta
        # migracao. Ligado por omissao para quem tem telemovel, desligado para
        # os restantes — e o superadministrador liga quando o numero existir.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("users", "User").objects.filter(
                phone__in=["", None]
            ).update(is_2fa_enabled=False),
            migrations.RunPython.noop,
        ),
    ]
