/** Texto do site público do BusUp — o desenho "Céu".
 *
 * COPIADO VERBATIM do protótipo `Landing BusUp - Ceu.dc.html`, em PT e EN.
 * A regra da entrega é explícita: "Nenhum texto novo inventado: o conteúdo dos
 * protótipos é para usar tal e qual". Onde o protótipo deixou um espaço por
 * preencher — os depoimentos dos operadores — o espaço vem para aqui como
 * está, marcado, em vez de ser preenchido por mim.
 *
 * Vive à parte de `landing/landing-copy.ts`, que é o dicionário da landing
 * antiga e continua a servir o que ainda não foi migrado.
 */

import type { Lang } from "../landing/useLandingPrefs";

const PT = {
  portalLogin: "Entrar no portal",
  navContact: "Contactos", navProduct: "Produto", navFeatures: "Funcionalidades", navWhy: "Porquê BusUp", navCases: "Casos", navPricing: "Preços",
  talkSales: "Entrar em contacto", buyTicket: "Comprar bilhete",
  heroBadge: "Bilhética digital · Moçambique",
  heroH1a: "Bilhetes, frota e receita",
  heroH1b: "numa só plataforma.",
  heroLead: "O BusUp digitaliza a venda e a validação de bilhetes no transporte de passageiros — do bairro à viagem internacional. O passageiro compra no telemóvel ou no agente; o operador vê cada viagem e cada metical, em tempo real.",
  heroLeadShort: "O passageiro compra no telemóvel ou no agente. O operador vê cada viagem e cada metical, em tempo real.",
  ctaPrimary: "Entrar em contacto", ctaSecondary: "Ver a plataforma",
  chips: ["QR no telemóvel", "Cartão NFC", "M-Pesa", "e-Mola"],
  tag1: "Cobrador", tag2: "Direcção", tag3: "Motorista", tag4: "Passageiro",
  ecoStripTitle: "Ecossistemas UpDigital",
  logosLead: "Construído sobre o ecossistema UpDigital",
  featH2: "Tudo o que a operação precisa, num só sistema.",
  featLead: "Venda, validação, cartões, receita e frota — sem folhas de Excel pelo meio.",
  f1t: "Venda em três canais", f1p: "Site, app do passageiro e agente no terreno. Pago com M-Pesa ou e-Mola em menos de um minuto.",
  f2t: "Validação a bordo", f2p: "QR ou cartão NFC confirmados em segundos, com a decisão registada na hora.",
  f3t: "Cartões físicos e digitais", f3p: "Cartões NFC e passes digitais QR, criados um a um ou importados de Excel.",
  f4t: "Receita em tempo real", f4p: "Cada bilhete fica registado. A tesouraria reconcilia sem esperar pelo fecho do dia.",
  f5t: "Frota e rotas no mapa", f5p: "Viaturas, motoristas e viagens com posição GPS e ocupação por lugar.",
  f5a: "Programação diária automática", f5b: "Ocupação por viatura e por lugar", f5c: "Histórico e auditoria de tudo",
  statsH2: "Porque é que os operadores escolhem o BusUp",
  statsLead: "Números do produto, não de marketing.",
  stats: [
    { v: "3", l: "canais de venda e validação" },
    { v: "2", l: "carteiras móveis integradas" },
    { v: "100%", l: "da receita registada" },
    { v: "0", l: "obras na frota actual" },
  ],
  stepsH2: "Começar em três passos",
  stepsLead: "Carregamos as suas rotas e horários; a operação arranca no mesmo dia.",
  stepsPanelTitle: "Portal de gestão",
  stepsPanelText: "Rotas, paragens, viaturas e tarifas configurados por nós, revistos por si.",
  steps: [
    { n: "01", title: "Configuração das rotas", text: "Importamos rotas, paragens, horários e tarifas da sua operação actual.", m1: "Nova rota", m1cta: "Guardar", m2: "Paragens", m2a: "Baixa", m2b: "Aeroporto" },
    { n: "02", title: "Equipa e dispositivos", text: "Perfis por função, POS dos agentes activados e cartões emitidos.", m1: "Novo agente", m1cta: "Activar", m2: "Dispositivos", m2a: "POS-04 ligado", m2b: "POS-07 ligado" },
    { n: "03", title: "Vender e acompanhar", text: "A venda arranca e a direcção acompanha a receita em tempo real.", m1: "Relatório", m1cta: "Exportar", m2: "Receita", m2a: "Fecho conferido", m2b: "Auditoria activa" },
  ],
  casesH2: "Resultados reais, impacto real",
  casesLead: "Espaço reservado para depoimentos de operadores. Envie-nos as citações e atribuições reais e substituímos.",
  cases: [
    { kind: "Urbano · Maputo", quote: "[Depoimento a preencher] Espaço para o que o operador diz sobre o fim do dinheiro vivo a bordo.", who: "Nome, cargo — operador urbano" },
    { kind: "Interurbano", quote: "[Depoimento a preencher] Espaço para o que muda no fecho de contas e na reconciliação diária.", who: "Nome, cargo — operador interurbano" },
    { kind: "Institucional", quote: "[Depoimento a preencher] Espaço para o que muda no controlo do embarque escolar ou de colaboradores.", who: "Nome, cargo — instituição" },
  ],
  priceH2: "Preços por operação, não por tabela",
  priceLead: "O valor depende da frota, dos canais de venda e do volume. Sem custo de licença por telemóvel do passageiro.",
  plans: [
    { name: "Urbano", price: "Sob consulta", unit: "Frotas até 20 viaturas, venda no agente e QR no telemóvel.", cta: "Pedir proposta", items: ["Portal de gestão", "App POS para agentes", "M-Pesa e e-Mola", "Relatórios diários"] },
    { name: "Interurbano", price: "Sob consulta", unit: "Rotas longas com lugar marcado e bilhete em PDF.", featured: true, badge: "Mais procurado", cta: "Pedir proposta", items: ["Tudo do plano Urbano", "Lugar marcado e mapa de lugares", "Bilhete PDF com QR", "Cartões NFC e digitais"] },
    { name: "Institucional", price: "Sob consulta", unit: "Empresas, escolas e frotas com contrato próprio.", cta: "Entrar em contacto", items: ["Tudo do plano Interurbano", "Pacotes e subsídios", "Perfis e permissões por função", "Suporte dedicado local"] },
  ],
  faqH2: "Perguntas que os operadores fazem",
  faqLead: "Se faltar alguma, escreva-nos — respondemos no mesmo dia útil.",
  faqs: [
    { q: "É preciso instalar equipamento nas viaturas?", a: "Não. A validação corre na app POS do agente ou do motorista, num telemóvel Android comum. Cartões NFC e QR funcionam com o mesmo aparelho." },
    { q: "Funciona sem rede?", a: "A venda exige rede para o pagamento, mas a validação a bordo tolera falhas: o registo é guardado no dispositivo e sincroniza quando a ligação volta." },
    { q: "Que pagamentos são aceites?", a: "M-Pesa e e-Mola através da Payless, além de dinheiro no agente e saldo em carteira ou cartão." },
    { q: "O passageiro tem de criar conta?", a: "Não. A compra pública funciona sem registo — o bilhete chega em PDF com QR. Contas e cartões são opcionais para passageiros frequentes." },
    { q: "Quem tem acesso a quê?", a: "Perfis com permissões por função e registo de auditoria de quem fez o quê, em todo o portal." },
  ],
  formH2: "Vamos ver isto na sua operação.",
  formLead: "Preenchemos a plataforma com as suas rotas e horários e mostramos o fluxo completo — venda, embarque e fecho de contas.",
  formFacts: ["A plataforma com os seus dados", "Instalação sem obra na frota", "Suporte local em Moçambique"],
  formTitle: "Pedido de contacto",
  fName: "Nome", fCompany: "Empresa", fPhone: "Telefone", fFleet: "Viaturas na frota", fMsg: "Mensagem",
  formCta: "Enviar pedido",
  formNote: "Respondemos em dias úteis, das 08h00 às 17h00 (CAT).",
  sentTitle: "Pedido enviado.", sentText: "A equipa comercial responde no próximo dia útil.",
  commercial: "Comercial",
  ctaH2: "Leve o BusUp para a sua frota.",
  ctaLead: "Mostramos a plataforma a operar com as suas rotas, os seus horários e os seus números.",
  ctaContact: "Entrar em contacto", ctaPricing: "Ver preços",
  mapPanel: "Mapa da frota", mapPlaceholder: "Screenshot do mapa Leaflet/OpenStreetMap do portal a inserir",
  ecoLabel: "Desenvolvido por",
  ecoH2: "Quem constrói o BusUp",
  ecoLead: "O BusUp é desenvolvido pela UpDigital, Limitada — empresa moçambicana de software com sede na Matola. A mesma engenharia sustenta os outros produtos do grupo.",
  ecoNote: "Suporte local: quem escreve o software é quem atende o operador.",
  ecoItems: [
    { logo: "assets/logo-payup.png", name: "PayUp", url: "https://payup.updigital.co.mz" },
    { logo: "assets/logo-cashup.png", name: "CashUp", url: "https://cashup.updigital.co.mz" },
    { logo: "assets/logo-gateup.png", name: "GateUp", url: "https://gateup.updigital.co.mz" },
    { logo: "assets/logo-vura.png", name: "Vura", url: "https://vura.updigital.co.mz" },
    { logo: "assets/logo-ossoma.png", name: "Ossoma", url: "https://ossoma.updigital.co.mz" },
  ],
  footerAbout: "Plataforma de bilhética digital para o transporte de passageiros. Desenvolvido em Moçambique.",
  footerProduct: "Produto", footerAccess: "Acesso", footerContact: "Contacto",
  footerPortal: "Portal de gestão", footerApps: "Descarregar apps",
  poweredBy: "Desenvolvido por", footerEco: "Ecossistema",
  rights: "Todos os direitos reservados.",
};

const EN: typeof PT = {
  portalLogin: "Sign in to the portal",
  navContact: "Contact", navProduct: "Product", navFeatures: "Features", navWhy: "Why BusUp", navCases: "Cases", navPricing: "Pricing",
  talkSales: "Get in touch", buyTicket: "Buy a ticket",
  heroBadge: "Digital ticketing · Mozambique",
  heroH1a: "Tickets, fleet and revenue",
  heroH1b: "on a single platform.",
  heroLead: "BusUp digitises ticket sales and validation in passenger transport — from the neighbourhood route to the cross-border trip. Passengers buy on their phone or from an agent; the operator sees every trip and every metical, in real time.",
  heroLeadShort: "Passengers buy on their phone or from an agent. The operator sees every trip and every metical, in real time.",
  ctaPrimary: "Get in touch", ctaSecondary: "See the platform",
  chips: ["QR on the phone", "NFC card", "M-Pesa", "e-Mola"],
  tag1: "Agent", tag2: "Management", tag3: "Driver", tag4: "Passenger",
  ecoStripTitle: "UpDigital ecosystems",
  logosLead: "Built on the UpDigital ecosystem",
  featH2: "Everything the operation needs, in one system.",
  featLead: "Sales, validation, cards, revenue and fleet — with no spreadsheets in between.",
  f1t: "Sales across three channels", f1p: "Website, passenger app and agent on the ground. Paid with M-Pesa or e-Mola in under a minute.",
  f2t: "Validation on board", f2p: "QR or NFC card confirmed in seconds, with the decision recorded on the spot.",
  f3t: "Physical and digital cards", f3p: "NFC cards and digital QR passes, created one by one or imported from Excel.",
  f4t: "Revenue in real time", f4p: "Every ticket is recorded. Treasury reconciles without waiting for the daily close.",
  f5t: "Fleet and routes on the map", f5p: "Vehicles, drivers and trips with GPS position and seat-level occupancy.",
  f5a: "Automatic daily scheduling", f5b: "Occupancy per vehicle and per seat", f5c: "Full history and audit trail",
  statsH2: "Why operators choose BusUp",
  statsLead: "Product numbers, not marketing ones.",
  stats: [
    { v: "3", l: "sales and validation channels" },
    { v: "2", l: "mobile wallets integrated" },
    { v: "100%", l: "of revenue recorded" },
    { v: "0", l: "changes to your current fleet" },
  ],
  stepsH2: "Get started in three steps",
  stepsLead: "We load your routes and schedules; the operation starts the same day.",
  stepsPanelTitle: "Management portal",
  stepsPanelText: "Routes, stops, vehicles and fares configured by us, reviewed by you.",
  steps: [
    { n: "01", title: "Route configuration", text: "We import routes, stops, schedules and fares from your current operation.", m1: "New route", m1cta: "Save", m2: "Stops", m2a: "Downtown", m2b: "Airport" },
    { n: "02", title: "Team and devices", text: "Roles per function, agent POS activated and cards issued.", m1: "New agent", m1cta: "Activate", m2: "Devices", m2a: "POS-04 online", m2b: "POS-07 online" },
    { n: "03", title: "Sell and follow through", text: "Selling starts and management follows revenue in real time.", m1: "Report", m1cta: "Export", m2: "Revenue", m2a: "Close checked", m2b: "Audit active" },
  ],
  casesH2: "Real results, real impact",
  casesLead: "Placeholder for operator testimonials. Send us the real quotes and attributions and we will swap them in.",
  cases: [
    { kind: "Urban · Maputo", quote: "[Testimonial to be filled] Space for what the operator says about ending cash on board.", who: "Name, role — urban operator" },
    { kind: "Intercity", quote: "[Testimonial to be filled] Space for what changes in the daily close and reconciliation.", who: "Name, role — intercity operator" },
    { kind: "Institutional", quote: "[Testimonial to be filled] Space for what changes in school or staff boarding control.", who: "Name, role — institution" },
  ],
  priceH2: "Priced per operation, not per table",
  priceLead: "The figure depends on fleet size, sales channels and volume. No licence cost per passenger phone.",
  plans: [
    { name: "Urban", price: "On request", unit: "Fleets up to 20 vehicles, agent sales and QR on the phone.", cta: "Request a quote", items: ["Management portal", "POS app for agents", "M-Pesa and e-Mola", "Daily reports"] },
    { name: "Intercity", price: "On request", unit: "Long routes with assigned seats and PDF tickets.", featured: true, badge: "Most requested", cta: "Request a quote", items: ["Everything in Urban", "Assigned seats and seat map", "PDF ticket with QR", "NFC and digital cards"] },
    { name: "Institutional", price: "On request", unit: "Companies, schools and fleets under contract.", cta: "Get in touch", items: ["Everything in Intercity", "Packages and subsidies", "Roles and permissions", "Dedicated local support"] },
  ],
  faqH2: "Questions operators ask",
  faqLead: "If one is missing, write to us — we answer the same business day.",
  faqs: [
    { q: "Do we need to install equipment on the vehicles?", a: "No. Validation runs in the agent or driver POS app on an ordinary Android phone. NFC cards and QR work on the same device." },
    { q: "Does it work without a connection?", a: "Sales need a connection for payment, but on-board validation tolerates outages: the record is kept on the device and syncs when the link returns." },
    { q: "Which payments are accepted?", a: "M-Pesa and e-Mola through Payless, plus cash with an agent and wallet or card balance." },
    { q: "Does the passenger need an account?", a: "No. Public purchase works without registration — the ticket arrives as a PDF with a QR code. Accounts and cards are optional for frequent passengers." },
    { q: "Who has access to what?", a: "Roles with permissions per function and an audit record of who did what, across the whole portal." },
  ],
  formH2: "Let us see this on your operation.",
  formLead: "We fill the platform with your routes and schedules and show the full flow — sale, boarding and daily close.",
  formFacts: ["The platform with your own data", "Installed with no fleet retrofit", "Local support in Mozambique"],
  formTitle: "Contact request",
  fName: "Name", fCompany: "Company", fPhone: "Phone", fFleet: "Vehicles in fleet", fMsg: "Message",
  formCta: "Send request",
  formNote: "We reply on business days, 08:00 to 17:00 (CAT).",
  sentTitle: "Request sent.", sentText: "The sales team replies on the next business day.",
  commercial: "Sales",
  ctaH2: "Bring BusUp to your fleet.",
  ctaLead: "We show the platform running on your routes, your schedules and your numbers.",
  ctaContact: "Get in touch", ctaPricing: "See pricing",
  mapPanel: "Fleet map", mapPlaceholder: "Screenshot of the portal's Leaflet/OpenStreetMap view to be added",
  ecoLabel: "Built by",
  ecoH2: "Who builds BusUp",
  ecoLead: "BusUp is built by UpDigital, Limitada — a Mozambican software company based in Matola. The same engineering supports the group's other products.",
  ecoNote: "Local support: the people who write the software are the people who answer the operator.",
  ecoItems: [
    { logo: "assets/logo-payup.png", name: "PayUp", url: "https://payup.updigital.co.mz" },
    { logo: "assets/logo-cashup.png", name: "CashUp", url: "https://cashup.updigital.co.mz" },
    { logo: "assets/logo-gateup.png", name: "GateUp", url: "https://gateup.updigital.co.mz" },
    { logo: "assets/logo-vura.png", name: "Vura", url: "https://vura.updigital.co.mz" },
    { logo: "assets/logo-ossoma.png", name: "Ossoma", url: "https://ossoma.updigital.co.mz" },
  ],
  footerAbout: "Digital ticketing platform for passenger transport. Built in Mozambique.",
  footerProduct: "Product", footerAccess: "Access", footerContact: "Contact",
  footerPortal: "Management portal", footerApps: "Download apps",
  poweredBy: "Powered by", footerEco: "Ecosystem",
  rights: "All rights reserved.",
};

const DICIONARIOS: Record<Lang, typeof PT> = { pt: PT, en: EN };

export function copyBusUp(lang: Lang) {
  return DICIONARIOS[lang] ?? PT;
}

export type CopyBusUp = typeof PT;
