# Generated by Django 4.2.23 on 2026-05-26 16:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('balance_cached', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='MZN', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('blocked', 'Bloqueada'), ('closed', 'Encerrada')], default='active', max_length=16)),
                ('passenger_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='passengers.passengeraccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('topup', 'Recarga'), ('fare_debit', 'Debito de Viagem'), ('refund', 'Reembolso'), ('reversal', 'Reversao'), ('adjustment', 'Ajuste'), ('card_transfer', 'Transferencia de Cartao'), ('fee', 'Taxa')], max_length=24)),
                ('direction', models.CharField(choices=[('credit', 'Credito'), ('debit', 'Debito')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('failed', 'Falhada'), ('reversed', 'Revertida')], default='confirmed', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['wallet', 'status'], name='wallets_wal_wallet__57ec3f_idx'), models.Index(fields=['reference'], name='wallets_wal_referen_41fe73_idx')],
            },
        ),
    ]
