# Generated by Django 4.2.23 on 2026-05-26 19:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('passengers', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentagem'), ('fixed_amount', 'Valor Fixo'), ('free_trips', 'Viagens Gratis')], max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('max_trips', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PassengerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('special_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('trips_used', models.PositiveIntegerField(default=0)),
                ('trips_remaining', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('exhausted', 'Esgotado')], default='active', max_length=16)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='packages.package')),
                ('passenger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='passengers.passengeraccount')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_subscriptions', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-activated_at',),
                'indexes': [models.Index(fields=['passenger_account', 'status'], name='packages_pa_passeng_0d7d61_idx'), models.Index(fields=['status', 'expires_at'], name='packages_pa_status_112e09_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='packages.package')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_routes', to='routes.route')),
            ],
            options={
                'unique_together': {('package', 'route')},
            },
        ),
    ]
