# Generated by Django 4.2.23 on 2026-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packageroute',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='packageroute',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('package', 'route'), name='uq_package_route_active'),
        ),
    ]
