# Generated by Django 4.2.23 on 2026-05-26 16:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('single_trip', 'Viagem Avulsa'), ('daily_pass', 'Passe Diario'), ('weekly_pass', 'Passe Semanal'), ('monthly_pass', 'Passe Mensal')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=32)),
                ('passenger_class', models.CharField(choices=[('standard', 'Normal'), ('student', 'Estudante'), ('senior', 'Idoso'), ('child', 'Crianca')], default='standard', max_length=16)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Preco Fixo'), ('origin_destination', 'Origem/Destino'), ('distance', 'Distancia'), ('zone', 'Zona')], default='fixed', max_length=24)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_per_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('destination_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fare_rules_destination', to='routes.stop')),
                ('fare_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fares.fareproduct')),
                ('origin_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fare_rules_origin', to='routes.stop')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fare_rules', to='routes.route')),
            ],
            options={
                'ordering': ('-priority', '-created_at'),
            },
        ),
    ]
