# Generated by Django 4.2.23 on 2026-06-04 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0004_adminfee_code_active_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminfee',
            new_name='fares_admin_kind_a52de4_idx',
            old_name='adminfee_kind_idx',
        ),
        migrations.AlterField(
            model_name='adminfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adminfee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminfee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminfee',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
