# Generated by Django 4.2.23 on 2026-08-18 11:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0006_exchangerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='rounding_step',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
