# Generated by Django 5.1.4 on 2026-08-28 10:41

import apps.cms.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(choices=[('header', 'Cabecalho'), ('footer_product', 'Rodape · Produto'), ('footer_contact', 'Rodape · Contacto'), ('footer_eco', 'Rodape · Ecossistema')], max_length=32, unique=True)),
                ('label', models.JSONField(default=apps.cms.models.empty_i18n)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.JSONField(default=apps.cms.models.empty_i18n)),
                ('urban', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('intercity', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('institutional', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(upload_to='cms/media/')),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('alt', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('folder', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EcoSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='published', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('note', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.mediaasset')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.JSONField(default=apps.cms.models.empty_i18n)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisao'), ('scheduled', 'Agendado'), ('published', 'Publicado')], default='draft', max_length=16)),
                ('template', models.CharField(choices=[('landing', 'Landing'), ('pricing', 'Precos'), ('contact', 'Contactos'), ('apps', 'Apps'), ('generic', 'Generica')], default='generic', max_length=16)),
                ('locales', models.JSONField(default=apps.cms.models.default_locales)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.JSONField(default=apps.cms.models.empty_i18n)),
                ('href', models.CharField(blank=True, default='', max_length=400)),
                ('position', models.PositiveIntegerField(default=0)),
                ('target', models.CharField(blank=True, default='', max_length=10)),
                ('visible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.page')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('heroi', 'Heroi'), ('logos', 'Faixa de logos'), ('recursos', 'Funcionalidades'), ('porque', 'Porque BusUp'), ('casos', 'Casos'), ('precos', 'Precos'), ('faq', 'FAQ'), ('form', 'Formulario'), ('eco', 'Ecossistema'), ('cta', 'CTA'), ('richtext', 'Texto'), ('media', 'Media')], max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.page')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cms.page')),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.pageversion')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='page',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.pageversion'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.JSONField(default=apps.cms.models.empty_i18n)),
                ('price_label', models.JSONField(default=apps.cms.models.empty_i18n)),
                ('unit', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('cta_label', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('items', models.JSONField(blank=True, default=apps.cms.models.empty_i18n_list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('highlighted', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ScheduledPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(choices=[('page', 'Pagina'), ('plan', 'Plano'), ('eco_system', 'Sistema do ecossistema')], default='page', max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('done', 'Publicada'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='scheduled', max_length=16)),
                ('result', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('run_at',),
            },
        ),
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('description', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('slug', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('keywords', models.JSONField(blank=True, default=apps.cms.models.empty_i18n)),
                ('no_index', models.BooleanField(default=False)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.mediaasset')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='cms.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['folder', '-created_at'], name='cms_mediaas_folder_36a9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['page', 'position'], name='cms_pageblo_page_id_a04e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(fields=('page', 'number'), name='cms_versao_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='cms_page_slug_unico_activo'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['status', 'run_at'], name='cms_schedul_status_09cdcf_idx'),
        ),
    ]
