# Generated by Django 4.2.23 on 2026-08-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='type',
            field=models.CharField(choices=[('heroi', 'Heroi'), ('logos', 'Faixa de logos'), ('recursos', 'Funcionalidades'), ('passos', 'Comecar em tres passos'), ('porque', 'Porque BusUp'), ('casos', 'Casos'), ('precos', 'Precos'), ('faq', 'FAQ'), ('form', 'Formulario'), ('eco', 'Ecossistema'), ('cta', 'CTA'), ('richtext', 'Texto'), ('media', 'Media')], max_length=16),
        ),
    ]
