# Generated by Django 4.2.23 on 2026-05-26 16:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payer_phone', models.CharField(max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('route_code', models.CharField(blank=True, max_length=32)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('origin_stop', models.CharField(blank=True, max_length=255)),
                ('destination_stop', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('payment_pending', 'Pagamento Pendente'), ('paid', 'Pago'), ('issued', 'Emitido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='draft', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('linked_passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_checkouts', to='passengers.passengeraccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DigitalTravelPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('route_code', models.CharField(blank=True, max_length=32)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('origin_stop', models.CharField(blank=True, max_length=255)),
                ('destination_stop', models.CharField(blank=True, max_length=255)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('used', 'Usado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='active', max_length=16)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('delivery_channel', models.CharField(choices=[('sms', 'SMS'), ('app', 'App'), ('link', 'Link')], default='sms', max_length=8)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('guest_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_passes', to='guest_checkouts.guestcheckout')),
                ('passenger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_passes', to='passengers.passengeraccount')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_passes', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='guestcheckout',
            index=models.Index(fields=['payer_phone', 'status'], name='guest_check_payer_p_0c7f25_idx'),
        ),
        migrations.AddIndex(
            model_name='guestcheckout',
            index=models.Index(fields=['reference'], name='guest_check_referen_1eb9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaltravelpass',
            index=models.Index(fields=['token_hash'], name='guest_check_token_h_26ffd8_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaltravelpass',
            index=models.Index(fields=['status', 'valid_until'], name='guest_check_status_ae7c4a_idx'),
        ),
    ]
