# Generated by Codex on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
        ("guest_checkouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestcheckout",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_checkouts",
                to="trips.trip",
            ),
        ),
        migrations.AddField(
            model_name="digitaltravelpass",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="travel_passes",
                to="trips.trip",
            ),
        ),
    ]
