# Generated by Django 4.2.23 on 2026-05-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_stop_active_constraints'),
        ('guest_checkouts', '0002_guestcheckout_trip_digitaltravelpass_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltravelpass',
            name='destination_stop_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_passes_destination', to='routes.stop'),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='origin_stop_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_passes_origin', to='routes.stop'),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='destination_stop_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_checkouts_destination', to='routes.stop'),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='origin_stop_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_checkouts_origin', to='routes.stop'),
        ),
    ]
