# Generated by Django 4.2.23 on 2026-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkouts', '0003_digitaltravelpass_destination_stop_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltravelpass',
            name='departure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='document_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='document_type',
            field=models.CharField(blank=True, choices=[('bi', 'Bilhete de Identidade'), ('passport', 'Passaporte'), ('dire', 'DIRE'), ('cedula', 'Cedula'), ('other', 'Outro')], max_length=16),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='seat_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='passengers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
