# Generated by Django 4.2.23 on 2026-07-29 13:08

from django.db import migrations, models


def _backfill_short_codes(apps, schema_editor):
    """Preenche o codigo curto dos bilhetes ja emitidos.

    Sem isto, os bilhetes anteriores continuariam a depender do fallback por
    referencia do checkout — que e precisamente o que falhava em compras de
    varios bilhetes.
    """
    from apps.guest_checkouts.ticket_codes import ticket_reference, ticket_short_code

    Pass = apps.get_model("guest_checkouts", "DigitalTravelPass")
    updated = []
    for tp in Pass.objects.filter(short_code="").iterator(chunk_size=500):
        try:
            tp.short_code = ticket_short_code(ticket_reference(tp))
        except Exception:
            continue
        updated.append(tp)
        if len(updated) >= 500:
            Pass.objects.bulk_update(updated, ["short_code"])
            updated = []
    if updated:
        Pass.objects.bulk_update(updated, ["short_code"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkouts', '0004_digitaltravelpass_departure_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltravelpass',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddIndex(
            model_name='digitaltravelpass',
            index=models.Index(fields=['short_code', 'status'], name='guest_check_short_c_f9b21c_idx'),
        ),
        migrations.RunPython(_backfill_short_codes, _noop),
    ]
