# Generated by Django 4.2.23 on 2026-07-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkouts', '0005_digitaltravelpass_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltravelpass',
            name='display_currency',
            field=models.CharField(default='MZN', max_length=3),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='display_fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='display_currency',
            field=models.CharField(default='MZN', max_length=3),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='display_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
