# Generated by Django 4.2.23 on 2026-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkouts', '0006_digitaltravelpass_display_currency_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guestcheckout',
            index=models.Index(fields=['trip', 'status'], name='guest_check_trip_id_fe54d4_idx'),
        ),
        migrations.AddIndex(
            model_name='guestcheckout',
            index=models.Index(fields=['created_at'], name='guest_check_created_7b51fa_idx'),
        ),
    ]
