# Generated by Django 4.2.23 on 2026-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkouts', '0007_guestcheckout_guest_check_trip_id_fe54d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltravelpass',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='digitaltravelpass',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
