# Generated by Django 4.2.23 on 2026-08-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_triprevenueclosure_manifest_and_more'),
        ('guest_checkouts', '0008_digitaltravelpass_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltravelpass',
            name='leg',
            field=models.CharField(choices=[('outbound', 'Ida'), ('return', 'Volta')], default='outbound', max_length=8),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='return_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_checkouts_return', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='return_unit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
