# Generated by Django 4.2.23 on 2026-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkouts', '0009_ida_e_volta'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcheckout',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestcheckout',
            name='terms_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
