# Generated by Django 4.2.23 on 2026-08-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('guest_checkouts', '0010_aceitacao_dos_termos'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcheckout',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='shifts.shift'),
        ),
    ]
