# Generated by Django 4.2.23 on 2026-08-31 13:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0012_trip_direction'),
        ('devices', '0003_alter_device_activation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('float_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('counted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tickets_count', models.PositiveIntegerField(default=0)),
                ('validations_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado'), ('verified', 'Conferido')], db_index=True, default='open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='trips.agent')),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='devices.device')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_opened', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='trips.vehicle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
                'indexes': [models.Index(fields=['agent_user', 'status'], name='shifts_shif_agent_u_6f6280_idx'), models.Index(fields=['status', 'opened_at'], name='shifts_shif_status_ba3a05_idx')],
            },
        ),
    ]
