# Generated by Django 4.2.23 on 2026-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
