# Generated by Django 4.2.23 on 2026-08-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_brandingsettings_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='company_website',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='contact_phones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_closing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
