# Generated by Django 4.2.23 on 2026-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_termos_tpmtur'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_closing_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_intro_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='terms_sections_en',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
