# Generated by Django 4.2.23 on 2026-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='stop',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
