# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_alter_route_code_alter_stop_code"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE routes_routestop "
                        "DROP CONSTRAINT IF EXISTS routes_routestop_route_id_direction_sequence_1626c93c_uniq"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="routestop",
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="routestop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("route", "direction", "sequence"),
                name="uq_route_stop_sequence_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="routestop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("route", "direction", "stop"),
                name="uq_route_stop_once_active",
            ),
        ),
    ]
