# Generated by Django 4.2.23 on 2026-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_stop_active_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='service_type',
            field=models.CharField(choices=[('urban', 'Urbano / Interurbano'), ('interprovincial', 'Interprovincial'), ('international', 'Internacional')], default='urban', help_text='Determina se o passageiro escolhe o lugar na compra.', max_length=20),
        ),
    ]
