# Generated by Django 4.2.23 on 2026-05-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('device_type', models.CharField(choices=[('urovo_i9100_pos', 'UROVO I9100 POS'), ('sunmi_v2s_pos', 'SUNMI V2s POS'), ('mobile_app', 'App Mobile'), ('admin_browser', 'Browser Admin')], max_length=24)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=64)),
                ('imei', models.CharField(blank=True, max_length=32)),
                ('android_id', models.CharField(blank=True, max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('self_onboarded', 'Self-Onboarded'), ('pending_activation', 'Pendente Activacao'), ('pending_configuration', 'Pendente Configuracao'), ('active', 'Activo'), ('rejected', 'Rejeitado'), ('blocked', 'Bloqueado'), ('retired', 'Retirado')], default='self_onboarded', max_length=24)),
                ('activation_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('app_version_code', models.PositiveIntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeviceActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activation_code', models.CharField(db_index=True, max_length=12)),
                ('requested_serial_number', models.CharField(max_length=128)),
                ('requested_model', models.CharField(blank=True, max_length=64)),
                ('requested_manufacturer', models.CharField(blank=True, max_length=64)),
                ('requested_imei', models.CharField(blank=True, max_length=32)),
                ('requested_android_id', models.CharField(blank=True, max_length=64)),
                ('requested_capabilities', models.JSONField(blank=True, default=list)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='devices.device')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type', 'status'], name='devices_dev_device__3e2531_idx'),
        ),
    ]
