# Generated by Django 4.2.23 on 2026-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_heading_device_last_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='activation_code',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('serial_number',), name='uq_device_serial_active'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('activation_code',), name='uq_device_activation_code_active'),
        ),
    ]
