# Generated by Django 4.2.23 on 2026-07-29 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interest', models.CharField(choices=[('operator', 'Operador de transporte'), ('company', 'Empresa'), ('school', 'Escola ou instituicao'), ('other', 'Outro')], default='operator', max_length=16)),
                ('fleet_size', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contactado'), ('qualified', 'Qualificado'), ('closed', 'Fechado')], default='new', max_length=16)),
                ('source', models.CharField(default='landing', max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='leads_servi_status_d7ac4f_idx')],
            },
        ),
    ]
