# Generated by Django 4.2.23 on 2026-07-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('contact', 'Formulário de contacto'), ('waitlist', 'Lista de espera da app')], default='contact', max_length=16)),
                ('profile', models.CharField(blank=True, choices=[('passageiro', 'Passageiro'), ('operador', 'Operador de transporte'), ('municipio', 'Município / Entidade pública'), ('parceiro', 'Parceiro / Ponto de recarga'), ('imprensa', 'Imprensa'), ('outro', 'Outro')], max_length=32)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('locale', models.CharField(blank=True, max_length=8)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto / Lead',
                'verbose_name_plural': 'Contactos / Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'handled'], name='leads_conta_source_a5ebff_idx'), models.Index(fields=['-created_at'], name='leads_conta_created_d3ab1b_idx')],
            },
        ),
    ]
