"""Os campos que o formulario do site ja pedia e nao tinham onde ficar.

`role` (Cargo) era enviado pelo site e deitado fora — nao havia coluna nem
campo no serializer. `topics` guarda o "O que quer ver", que o CMS declarava
como sendo `interest`: o formulario oferecia "Venda online" e a API respondia
400, porque `interest` diz QUEM contacta e nao o que a pessoa quer ver.
`operation_type` e o "Tipo de operacao" do desenho.

Os tres nascem vazios e nenhum mexe no que ja existe: `interest` mantem o
significado e os valores que tem em producao.
"""

# Generated by Django 4.2.23 on 2026-08-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('urban', 'Urbano'), ('intercity', 'Interurbano'), ('international', 'Internacional'), ('institutional', 'Empresa ou escola')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
