# Generated by Django 4.2.23 on 2026-05-26 16:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('trips', '0001_initial'),
        ('devices', '0001_initial'),
        ('guest_checkouts', '0001_initial'),
        ('passengers', '0001_initial'),
        ('wallets', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('validation_type', models.CharField(choices=[('card_pay_as_you_go', 'Cartao Pay-as-you-go'), ('qr_pay_as_you_go', 'QR Pay-as-you-go'), ('digital_travel_pass', 'Passe Digital'), ('guest_digital_travel_pass', 'Passe Digital Convidado')], max_length=32)),
                ('amount_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('denied', 'Negado')], max_length=16)),
                ('failure_reason', models.CharField(blank=True, choices=[('', ''), ('insufficient_balance', 'Saldo Insuficiente'), ('card_blocked', 'Cartao Bloqueado'), ('account_blocked', 'Conta Bloqueada'), ('pass_already_used', 'Passe Ja Usado'), ('pass_expired', 'Passe Expirado'), ('invalid_token', 'Token Invalido'), ('route_not_allowed', 'Rota Nao Permitida'), ('device_blocked', 'Dispositivo Bloqueado'), ('no_fare_found', 'Tarifa Nao Encontrada')], default='', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('wallet_transaction_ref', models.CharField(blank=True, max_length=64)),
                ('destination_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events_dest', to='routes.stop')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='devices.device')),
                ('digital_travel_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='guest_checkouts.digitaltravelpass')),
                ('origin_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events_origin', to='routes.stop')),
                ('passenger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='passengers.passengeraccount')),
                ('physical_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='cards.physicalcard')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='routes.route')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='trips.trip')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['validation_type', 'status'], name='validations_validat_f9705b_idx'), models.Index(fields=['route', 'created_at'], name='validations_route_i_dc17b3_idx'), models.Index(fields=['device', 'created_at'], name='validations_device__d7e89d_idx')],
            },
        ),
    ]
