# Generated by Django 4.2.23 on 2026-05-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_remove_physicalcard_passenger_account_and_more'),
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationevent',
            name='physical_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='cards.card'),
        ),
    ]
