# Generated by Django 4.2.23 on 2026-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0002_alter_validationevent_physical_card'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='validationevent',
            index=models.Index(fields=['created_at'], name='validations_created_a230fc_idx'),
        ),
        migrations.AddIndex(
            model_name='validationevent',
            index=models.Index(fields=['status', 'created_at'], name='validations_status_a90cfe_idx'),
        ),
    ]
