# Generated by Django 4.2.23 on 2026-08-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validations', '0003_validationevent_validations_created_a230fc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationevent',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
