# Generated by Django 4.2.23 on 2026-08-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_validationevent_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationevent',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('', ''), ('insufficient_balance', 'Saldo Insuficiente'), ('card_blocked', 'Cartao Bloqueado'), ('account_blocked', 'Conta Bloqueada'), ('pass_already_used', 'Passe Ja Usado'), ('pass_expired', 'Passe Expirado'), ('invalid_token', 'Token Invalido'), ('route_not_allowed', 'Rota Nao Permitida'), ('device_blocked', 'Dispositivo Bloqueado'), ('no_fare_found', 'Tarifa Nao Encontrada'), ('no_ticket_for_route', 'Sem Bilhete Para Esta Rota')], default='', max_length=32),
        ),
    ]
