# Generated by Django 4.2.23 on 2026-05-26 16:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guest_checkouts', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('purpose', models.CharField(choices=[('mobile_wallet_topup', 'Recarga App'), ('pos_card_topup', 'Recarga POS'), ('guest_travel_pass_purchase', 'Bilhete Convidado'), ('app_travel_pass_purchase', 'Bilhete App'), ('direct_trip_payment', 'Pagamento Directo'), ('refund', 'Reembolso')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='MZN', max_length=3)),
                ('payer_phone', models.CharField(max_length=20)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('created', 'Criado'), ('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('failed', 'Falhado'), ('expired', 'Expirado'), ('reversed', 'Revertido')], default='created', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('guest_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='guest_checkouts.guestcheckout')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('raw_payload', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='received', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callbacks', to='payments.paymentintent')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_79eeea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['payer_phone'], name='payments_pa_payer_p_eeb364_idx'),
        ),
    ]
