# Generated by Django 4.2.23 on 2026-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['purpose', 'status', 'created_at'], name='payments_pa_purpose_2d6274_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider_reference'], name='payments_pa_provide_6dd94b_idx'),
        ),
    ]
