# Generated by Django 4.2.23 on 2026-05-26 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspenso')], default='active', max_length=16)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('planned_departure_at', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_at', models.DateTimeField(blank=True, null=True)),
                ('planned_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('boarding', 'Embarque'), ('departed', 'Em Viagem'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='scheduled', max_length=16)),
            ],
            options={
                'ordering': ('-planned_departure_at',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('registration', models.CharField(db_index=True, max_length=20)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'Em Manutencao'), ('retired', 'Retirado')], default='active', max_length=16)),
            ],
            options={
                'ordering': ('registration',),
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('registration',), name='uq_vehicle_reg_active'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.vehicle'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'status'], name='trips_trip_route_i_50d900_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['planned_departure_at'], name='trips_trip_planned_0b7a4d_idx'),
        ),
    ]
