# Generated by Django 4.2.23 on 2026-05-26 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_code_alter_stop_code'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('frequency_minutes', models.PositiveIntegerField(default=30)),
                ('days_of_week', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='trips.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='trips.vehicle')),
            ],
            options={
                'ordering': ('route', 'start_time'),
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.routeschedule'),
        ),
    ]
