# Generated by Django 4.2.23 on 2026-05-28 07:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0003_route_stop_active_constraints'),
        ('trips', '0003_vehicle_seated_standing_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='closure_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='pause_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('boarding', 'Embarque'), ('departed', 'Em Viagem'), ('paused', 'Em Repouso'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='scheduled', max_length=16),
        ),
        migrations.CreateModel(
            name='TripRevenueClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pause_seconds', models.PositiveIntegerField(default=0)),
                ('guest_checkout_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('app_pass_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('wallet_validation_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('direct_payment_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_revenue_closures', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_revenue_closures', to='trips.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_revenue_closures', to='routes.route')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_closure', to='trips.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_revenue_closures', to='trips.vehicle')),
            ],
            options={
                'ordering': ('-closed_at',),
                'indexes': [models.Index(fields=['route', 'closed_at'], name='trips_tripr_route_i_0dbd4d_idx'), models.Index(fields=['vehicle', 'closed_at'], name='trips_tripr_vehicle_68e88e_idx'), models.Index(fields=['driver', 'closed_at'], name='trips_tripr_driver__a6ab8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('start', 'Inicio'), ('pause', 'Repouso'), ('resume', 'Retoma'), ('close', 'Fecho')], max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='trips.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='trips.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['trip', 'event_type'], name='trips_tripa_trip_id_6d22a1_idx'), models.Index(fields=['driver', 'occurred_at'], name='trips_tripa_driver__c537e1_idx')],
            },
        ),
    ]
