# Generated by Django 4.2.23 on 2026-07-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_activation_code_and_more'),
        ('trips', '0006_vehicle_livrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='devices.device'),
        ),
    ]
