# Generated by Django 4.2.23 on 2026-07-30 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_trips_trip_driver__692693_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeschedule',
            name='frequency_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
