# Generated by Django 4.2.23 on 2026-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_routeschedule_frequency_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_row_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seat_layout',
            field=models.CharField(choices=[('1+1', '1 + 1'), ('1+2', '1 + 2'), ('2+1', '2 + 1'), ('2+2', '2 + 2'), ('2+3', '2 + 3'), ('3+2', '3 + 2')], default='2+2', help_text='Bancos de cada lado do corredor, ex.: 2+2, 1+2, 3+2.', max_length=8),
        ),
    ]
