# Generated by Django 4.2.23 on 2026-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_vehicle_last_row_seats_vehicle_seat_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprevenueclosure',
            name='manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='triprevenueclosure',
            name='passengers_aboard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triprevenueclosure',
            name='passengers_no_show',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripactivityevent',
            name='event_type',
            field=models.CharField(choices=[('start', 'Abertura do embarque'), ('depart', 'Partida'), ('pause', 'Repouso'), ('resume', 'Retoma'), ('close', 'Fecho')], max_length=16),
        ),
    ]
