import 'dart:async';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../core/api_client.dart';
import '../../core/device_info.dart';
import '../../core/providers.dart';
import '../../core/theme.dart';
import '../../core/theme_controller.dart';

/// Self-register the POS device and wait for the admin to allocate it.
///
/// The activation CODE is *generated by the admin in the portal* — the device
/// itself never displays it. We only show:
///   - device serial
///   - current status
///   - assigned agent (when admin already did it)
///   - a button to enter the code given by the admin
class OnboardingScreen extends ConsumerStatefulWidget {
  const OnboardingScreen({super.key});

  @override
  ConsumerState<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends ConsumerState<OnboardingScreen> {
  String? _serial;
  String _status = "registering";
  String? _agentName;
  String? _error;
  Timer? _pollTimer;
  bool _registering = true;

  @override
  void initState() {
    super.initState();
    Future.microtask(_register);
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

  Future<void> _register() async {
    setState(() {
      _error = null;
      _registering = true;
    });
    try {
      final fp = await readDeviceFingerprint();
      final api = ref.read(agentApiProvider);
      final res = await api.selfOnboard(
        serialNumber: fp.serialNumber,
        deviceType: fp.deviceType,
        modelName: fp.modelName,
        manufacturer: fp.manufacturer,
        androidId: fp.androidId,
        appVersion: '1.0.0',
        capabilities: const ['qr_scanner', 'camera'],
      );

      _serial = res['serial_number'] as String?;
      _status = (res['status'] as String?) ?? 'self_onboarded';

      if (_serial != null) {
        await ref.read(secureStoreProvider).saveDeviceSerial(_serial!);
      }

      if (_status == 'active') {
        if (mounted) context.go('/login');
        return;
      }

      _startPolling();
      if (mounted) setState(() => _registering = false);
    } on DioException catch (e) {
      setState(() {
        _error = ApiClient.extractError(e);
        _registering = false;
      });
    } catch (e) {
      setState(() {
        _error = e.toString();
        _registering = false;
      });
    }
  }

  void _startPolling() {
    _pollTimer?.cancel();
    _pollTimer = Timer.periodic(const Duration(seconds: 4), (_) => _poll());
  }

  Future<void> _poll() async {
    if (_serial == null) return;
    try {
      final res = await ref.read(agentApiProvider).deviceStatus(_serial!);
      final status = (res['status'] as String?) ?? _status;
      final agent = (res['agent_name'] as String?) ?? '';
      if (mounted) {
        setState(() {
          _status = status;
          _agentName = agent.isEmpty ? null : agent;
        });
      }
      if (status == 'active' && mounted) {
        _pollTimer?.cancel();
        context.go('/login');
      }
    } catch (_) {}
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final bg = isDark ? const Color(0xFF1A2A4E) : const Color(0xFFF7F4EE);
    final mainColor = isDark ? Colors.white : BuzUpColors.navy;
    final mutedColor = mainColor.withValues(alpha: 0.6);
    final brandLogo = isDark ? 'assets/buzup_dark.png' : 'assets/buzup_light.png';
    final upLogo = isDark ? 'assets/up_digital_dark.png' : 'assets/up_digital_light.png';

    return PopScope(
      canPop: false,
      child: Scaffold(
        backgroundColor: bg,
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            child: Column(
              children: [
                Align(
                  alignment: Alignment.topRight,
                  child: IconButton(
                    iconSize: 22,
                    icon: Icon(_themeIcon(ref.watch(themeControllerProvider)), color: mutedColor),
                    onPressed: () => ref.read(themeControllerProvider.notifier).toggle(),
                    tooltip: 'Mudar tema',
                  ),
                ),
                Image.asset(brandLogo,
                    height: 64,
                    errorBuilder: (_, __, ___) => Text('BuzUp',
                        style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: mainColor))),
                const SizedBox(height: 6),
                Container(width: 50, height: 2, color: BuzUpColors.orange),
                const SizedBox(height: 12),
                Text('Activacao do POS',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: mainColor)),
                const SizedBox(height: 14),
                Expanded(child: _buildBody(isDark, mainColor, mutedColor)),
                Padding(
                  padding: const EdgeInsets.only(top: 8, bottom: 4),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text('powered by ', style: TextStyle(color: mutedColor, fontSize: 11)),
                      Image.asset(upLogo,
                          height: 18,
                          errorBuilder: (_, __, ___) => Text('UpDigital',
                              style: TextStyle(color: mainColor, fontWeight: FontWeight.bold))),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildBody(bool isDark, Color mainColor, Color mutedColor) {
    if (_error != null) {
      return Center(
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          const Icon(Icons.error_outline, size: 56, color: BuzUpColors.danger),
          const SizedBox(height: 12),
          Text(_error!, textAlign: TextAlign.center, style: const TextStyle(color: BuzUpColors.danger)),
          const SizedBox(height: 16),
          FilledButton.icon(icon: const Icon(Icons.refresh), label: const Text('Tentar de novo'), onPressed: _register),
        ]),
      );
    }
    if (_registering) {
      return const Center(child: CircularProgressIndicator());
    }

    final waitingForAdmin = _agentName == null;
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: [
        // Big status pill
        Icon(
          waitingForAdmin ? Icons.hourglass_top : Icons.verified_user,
          size: 56,
          color: waitingForAdmin ? BuzUpColors.orange : BuzUpColors.success,
        ),
        const SizedBox(height: 4),
        Text(
          waitingForAdmin ? 'Aguarda alocacao' : 'Pronto para activar',
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: mainColor),
        ),
        const SizedBox(height: 4),
        Text(
          waitingForAdmin
              ? 'Pedir ao administrador que aloque este POS\na um agente para receber o codigo de activacao.'
              : 'O administrador deve fornecer o codigo\nde activacao. Toque em INTRODUZIR para abrir.',
          textAlign: TextAlign.center,
          style: TextStyle(color: mutedColor, fontSize: 12),
        ),

        // Device info card
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          decoration: BoxDecoration(
            color: isDark ? Colors.white12 : Colors.black.withValues(alpha: 0.05),
            borderRadius: BorderRadius.circular(10),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _row(Icons.tag, 'Serial', _serial ?? '-', mainColor, mutedColor),
              _row(Icons.flag, 'Estado', _statusLabel(_status), mainColor, mutedColor),
              if (_agentName != null)
                _row(Icons.person, 'Agente', _agentName!, mainColor, mutedColor),
            ],
          ),
        ),

        // Actions
        Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            OutlinedButton.icon(
              icon: const Icon(Icons.refresh, size: 16),
              label: const Text('Verificar agora', style: TextStyle(fontSize: 13)),
              onPressed: _poll,
            ),
            const SizedBox(height: 8),
            SizedBox(
              width: double.infinity,
              child: FilledButton.icon(
                icon: const Icon(Icons.key),
                label: const Text('INTRODUZIR CODIGO'),
                onPressed: () => context.go('/activation-code'),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _row(IconData icon, String label, String value, Color color, Color muted) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(children: [
        Icon(icon, color: muted, size: 14),
        const SizedBox(width: 6),
        Text('$label: ', style: TextStyle(color: muted, fontSize: 11)),
        Expanded(child: Text(value,
            overflow: TextOverflow.ellipsis,
            style: TextStyle(color: color, fontSize: 12, fontWeight: FontWeight.w600))),
      ]),
    );
  }

  String _statusLabel(String s) {
    switch (s) {
      case 'self_onboarded': return 'Registado, aguarda admin';
      case 'pending_activation': return 'Aguarda introducao do codigo';
      case 'active': return 'Activo';
      case 'blocked': return 'Bloqueado';
      case 'rejected': return 'Rejeitado';
      default: return s;
    }
  }

  IconData _themeIcon(ThemeMode mode) {
    switch (mode) {
      case ThemeMode.light: return Icons.light_mode;
      case ThemeMode.dark: return Icons.dark_mode;
      case ThemeMode.system: return Icons.brightness_auto;
    }
  }
}
