# Generated by Django 4.2.23 on 2026-06-04 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_recovery_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentdayclose',
            new_name='agent_api_a_agent_u_26fc87_idx',
            old_name='adc_agent_date_idx',
        ),
        migrations.RenameIndex(
            model_name='agentdayclose',
            new_name='agent_api_a_date_3f9446_idx',
            old_name='adc_date_agent_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverysession',
            new_name='agent_api_r_status_0fba6d_idx',
            old_name='recov_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverysession',
            new_name='agent_api_r_recover_5d5243_idx',
            old_name='recov_token_idx',
        ),
        migrations.AlterField(
            model_name='agentdayclose',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentdayclose',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentdayclose',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentdayclose',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recoverysession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recoverysession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverysession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recoverysession',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
